// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4nJfpR4S0KFIywMk95RKz6eGDO24-PfI',
    appId: '1:1019761517620:web:20b1008cba8f9ee7d05661',
    messagingSenderId: '1019761517620',
    projectId: 'project-2-3236b',
    authDomain: 'project-2-3236b.firebaseapp.com',
    storageBucket: 'project-2-3236b.appspot.com',
    measurementId: 'G-3P4JZ700WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPc6zVDALw3EAavfpFnxctfhNEVk8fE5E',
    appId: '1:1019761517620:android:3107459aaa7e7116d05661',
    messagingSenderId: '1019761517620',
    projectId: 'project-2-3236b',
    storageBucket: 'project-2-3236b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsh20dkIZuXAYuEBdDNjGalLqbIMZjZ0',
    appId: '1:1019761517620:ios:c1893c2d964c7de6d05661',
    messagingSenderId: '1019761517620',
    projectId: 'project-2-3236b',
    storageBucket: 'project-2-3236b.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsh20dkIZuXAYuEBdDNjGalLqbIMZjZ0',
    appId: '1:1019761517620:ios:c1893c2d964c7de6d05661',
    messagingSenderId: '1019761517620',
    projectId: 'project-2-3236b',
    storageBucket: 'project-2-3236b.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4nJfpR4S0KFIywMk95RKz6eGDO24-PfI',
    appId: '1:1019761517620:web:ba3eb77a2c2e0de1d05661',
    messagingSenderId: '1019761517620',
    projectId: 'project-2-3236b',
    authDomain: 'project-2-3236b.firebaseapp.com',
    storageBucket: 'project-2-3236b.appspot.com',
    measurementId: 'G-VKLG9LXFMC',
  );
}
